version: "3.9"

services:
  ve-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    image: nodejs
    container_name: ve-api
    restart: unless-stopped
    networks:
      - common_traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.ve-api.rule=Host(`votingescrow.equilibrefinance.com`)
      - traefik.http.routers.ve-api.tls.certresolver=letsencrypt
      - traefik.http.routers.ve-api.entryPoints=https
      - traefik.http.services.ve-api.loadbalancer.server.port=8381
      - traefik.docker.network=common_traefik
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
    ports:
      - "8381:8381/tcp"
    depends_on:
      - ve-api-cache
    volumes:
      - ./src:/app:rw
  ve-api-cache:
    container_name: ve-api-cache
    image: redis:6.2-alpine
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    volumes:
      - ${DATA_DIR}:/data
    networks:
      - common_traefik
networks:
  common_traefik:
    external: true
